config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#index'
  resources :books do
    resources :reviews
    resources :tweets
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews
  has_many :tweets
  belongs_to :user

  def publish
    book.update(is_published: true)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
  enum status: {draft: 0, published: 1}
  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :tweets

  def reviewed?(book)
    book.reviews.where(user_id: self.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:nickname, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(create_params)
    redirect_to action: 'index'
  end

  def show
    @book = Book.find(params[:id])
    @reviews = @book.reviews.includes(:user).where(status: 1)
  end

  private

  def create_params
    params.require(:book).permit(:title, :author, :start_date, :end_date).merge(user_id: current_user.id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.find(params[:book_id])
    @review = Review.new
  end

  def create
    book = Book.find(params[:book_id])
    ApplicationRecord.transaction do
      @review = book.reviews.create(create_params)
      case params[:commit]
      when '下書き保存'
        @review.draft!
      when '公開'
        @review.published!
      end # FIXME: buttonの日本語に依存しているのでよくない
    end
    redirect_to book_path(book.id)
    rescue => e
      render :text => e.message
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
    @book = @review.book
  end

  def update
    @review = Review.find(params[:id])
    ApplicationRecord.transaction do
      @review.update(update_params)
      case params[:commit]
      when '下書き保存'
        @review.draft!
      when '公開'
        @review.published!
      when '非公開'
        @review.archived!
      end
    end
    redirect_to book_path(@review.book.id)
    rescue => e
      render :text => e.message
  end

  private

  def create_params
    params.require(:review).permit(:title, :content).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:review).permit(:title, :content)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.find(params[:book_id])
    @tweets = @book.tweets.order("created_at DESC").limit(20)
    @tweet = @book.tweets.new
  end

  def create
    @book = Book.find(params[:book_id])
    @tweet = @book.tweets.create(create_params)
    redirect_to book_tweets_path
  end

  private

  def create_params
    params.require(:tweet).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.slim
= render partial: 'partial/book', collection: @books

= link_to '本を登録する', new_book_path

app/views/books/new.html.slim
= form_for @book do |f|
  = f.label :title
  = f.text_field :title, placeholder: "タイトル"

  = f.label :author
  = f.text_field :author, placeholder: "作者名"

  = f.label :start_date
  = f.date_field :start_date

  = f.label :end_date
  = f.date_field :end_date

  = f.submit 'send'

app/views/books/show.html.slim
h2
  = @book.title
h3
  = @book.author
p
  = @book.end_date
  | 終了

h3 書評一覧
- if @reviews.exists?
  ul#review_list
    = render partial: 'partial/review', collection: @reviews
- else
  p まだ投稿されていません


- if current_user.reviewed?(@book)
  = link_to '書評を編集する', edit_book_review_path(@book, @book.reviews.where(user_id: current_user.id).first.id)
- else
  = link_to '書評を投稿する', new_book_review_path(@book)

= link_to 'ディスカッション', book_tweets_path(@book)

app/views/layouts/application.html.slim
doctype html
html
  head
    link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"
    title
      | BookClub
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      nav class="navbar navbar-expand-lg navbar-light bg-light"
        = link_to root_path, class: 'navbar-brand' do
          span BOOK CLUB
        button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"
          span class="navbar-toggler-icon"
        div class="collapse navbar-collapse" id="navbarNavDropdown"
          ul class="navbar-nav"
            li class="nav-item dropdown"
              a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                = current_user.nickname
              div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"
                = link_to 'プロフィール', user_path(current_user.id), class: "dropdown-item"
                = link_to '設定', edit_user_registration_path, class: "dropdown-item"
                - if current_user
                  = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item"
                - else
                  = link_to 'ログイン', new_user_session_path, class: "dropdown-item"




    .container
      = yield
    script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"
    script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"

app/views/partial/_book.html.slim
h3
  = link_to book_path(book) do
    = book.title
p
  = book.author

app/views/partial/_review.html.slim
li
  = link_to book_review_path(review.book.id, review.id) do
    p
    |「
    = review.title
    | 」
    = link_to user_path(review.user.id) do
      = review.user.nickname

app/views/partial/_tweet.html.slim
li
  = tweet.content
  = link_to user_path(tweet.user_id) do
    = tweet.user.nickname
  = tweet.created_at

app/views/partial/_user_review.html.slim
li
  = link_to book_review_path(user_review.book.id, user_review.id) do
    p
    |「
    = user_review.title
    | 」

app/views/reviews/_review.html.slim
li
  = link_to book_review_path(review.book.id, review.id) do
    p
    |「
    = review.title
    | 」
    = review.user.nickname

app/views/reviews/edit.html.slim
= form_for [@book, @review] do |f|
  = f.label :title
  = f.text_field :title

  = f.label :author
  = f.text_area :content

  = f.submit '下書き保存'
  = f.submit '公開'

app/views/reviews/new.html.slim
= form_for [@book, @review] do |f|
  = f.label :title
  = f.text_field :title, placeholder: "タイトル"

  = f.label :author
  = f.text_area :content, placeholder: "書評を書いてください"

  = f.submit '下書き保存'
  = f.submit '公開'

app/views/reviews/show.html.slim
article
  h2
    = @review.title
  h3
    = @review.user.nickname
  p
    = @review.content

app/views/tweets/index.html.slim
h2
  = @book.title
h3
  = @book.author

ul#tweets_list
  = render partial: 'partial/tweet', collection: @tweets

= form_for [@book, @tweet], :url => {:action => 'create'} do |f|
  = f.text_area :content, placeholder: "質問やつぶやきを投稿しよう！"
  = f.submit '投稿'

app/views/users/show.html.slim
h2
  = @user.nickname
  h3 書評一覧
  - if @reviews.exists?
    h4 公開中
    ul#review_list
      = render partial: 'partial/user_review', collection: @reviews.published
    h4 下書き
    ul#review_list
      = render partial: 'partial/user_review', collection: @reviews.draft
  - else
    p まだ投稿されていません